# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RocketChatRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RocketChatRN
  pod 'AppAuth', '>= 0.91'

  target 'RocketChatRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RocketChatRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RocketChatRN-tvOS

  target 'RocketChatRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
